### ISSUE TITLE
GFTabBarView allow for disabling of animate  tabController

### ISSUE THREAD

**Issue by ivansempijja** [ionicfirebaseapp/getwidget#261]
Animation duration can be used to disable tabController animation and speed. 
Allow for one to set the animationDuration on the GFTabBarView, setting animationDuration to zero will
disable the animation on tabController

**Additional context**
[See Flutter PR](https://github.com/flutter/flutter/pull/91987)

**Comment by code-gene** [comment]
You can use GFTabBarView widget to control the speed of the animation. Please go through the below link,
[Link](https://github.com/flutter/flutter/issues/55625#issuecomment-619908700).

Instead of TabBarView use GFTabBarView which has a property called tabScrollDuration which can be used to control the speed. @ivansempijja
