### ISSUE TITLE
Can we support loading button?

### ISSUE THREAD

**Issue by yendangn** [ionicfirebaseapp/getwidget#52]
Hi team,

Can we support loading button widget like that?

https://github.com/leandroBorgesFerreira/LoadingButtonAndroid

Thank you very much.
Yen Dang

**Comment by PietechSolution** [comment]
Yes, we have a plan on this too to support loading as well but it takes some time as we busy with some other UI component. 

You can still customize the current button to implement that as well.

**Comment by RcDevRIL** [comment]
@PietechSolution @Sandipkakadiya
Hello guys, open to contributions?? Any guide to PR on your repository ?
I found this loading button beautiful so I tried to implement it, I have it on my [personal repo](https://github.com/RcDevRIL/MyFlutterStudies/blob/dev-animated-loading-button/loading_button/lib/ui/widgets/custom_loading_button.dart), but nothing related with your package yet. 

How should I make some contribution? I see that your buttons are way more complex than mine, of course it's a good thing. Can you give me some clues on which steps to go through in order to implement a new button of your package? :)

I'm a beginner but I may work on this because I love the idea of your package + the design @yendangn is submitting !

**Comment by PietechSolution** [comment]
Hi, We planning to add contributor to support this project. 

We will share more information on contribution , you may join our slack and we may discuss in detail on PR. 

We just added loader components too in our library 

https://docs.getflutter.dev/flutter-loader 

This loader just we need to call with button, as you see now both the components are available separately so just need hook them together.

Thanks

**Comment by RcDevRIL** [comment]
Sure please tell me when I can join!
Upon writing this comment, the Slack link was down on your [site](https://www.getflutter.dev/)...

This is output of my personal implementation now! I tried to improve customizations :) anyway, I will redo from scratch when we have a PR guide !
![Jf3iWeSGTY](https://user-images.githubusercontent.com/40863686/74093389-8f3d4900-4ad1-11ea-916e-7dca7f023cd4.gif)
